### ISSUE TITLE
Organize and get familiar with data for SNAP analysis

### ISSUE THREAD

**Issue by jbweaver** [jbweaver/wotc#1]
This task is to prepare the data to analyze the first question on SNAP. For this task, we want to:
1) Read through the WADC document docs to get familiar with which datasets and variables we will use.
2) Copy the appropriate raw data sets to the folder irp4/wotc/data/rawdata so we have our own copy in case there are updates (and to make sure we don't overwrite their data, since it isn't write protected). We already copied over a few of them. This includes the SNAP data, demographic file (mspf), wages and UI data.
3) Make a list of the variables of interest in each file that we will use later, as well as if there any flags from reading through the documentation that might be relevant to our later analysis

**Comment by jbweaver** [comment]
But wait! Ther eis no documentation. Where is it?

**Comment by jbweaver** [comment]
Documentation is at this link

**Comment by cmommaerts** [comment]
You didn't send me the link

**Comment by jbweaver** [comment]
[gerber and green.pdf](https://github.com/jbweaver/wotc/files/9418296/gerber.and.green.pdf)

**Comment by jbweaver** [comment]
@manishajain3 The documentation for the WADC data can be found here - https://www.irp.wisc.edu/wadc/ , where the most useful document is probably  this one (https://www.irp.wisc.edu/wp/wp-content/uploads/2022/04/WADC-Data-Documentation.pdf). 

The coding/data resource that I mentioned on the call is Gentzkow and Shapiro's code and data for the social sciences -- https://web.stanford.edu/~gentzkow/research/CodeAndData.pdf . They have a pretty good list of best practices, which I think is really good to read as a PhD student (I wish I had!) to get those started earlier.

**Comment by manishajain3** [comment]
Hi, had a ques about the eligibity condition of WOTC. From the proposal, it seemed to me that individuals aged 18 to 39 and whose family has received SNAP benefits for at least 3 of the 5 months prior to hiring are eligible. But acc to these documents (https://www.dol.gov/sites/dolgov/files/ETA/wotc/pdfs/WOTC_EligibilityDeskAid.pdf) (https://dlr.sd.gov/workforce_services/wotc/qualifying.aspx), it seems like the eligibility is the following?
1. aged 18 to 39
2. If (person's case is closed AND “able-bodied adult without dependents") is FALSE>>>should be a  member of a family that has received SNAP benefits for the
6-month period (continuous 6 month period) ending on the hiring date
3. If  (person's case is closed AND “able-bodied adult without dependents") is TRUE>>>should be a  member of a family that received SNAP benefits for atleast 3 months of the 5-month periodending on the hiring date. 

I didn't see any info on "able-bodied adult without dependents" status in the SNAP files in WADC

**Comment by cmommaerts** [comment]
Not sure the email version went through so re-posting directly:

Great question -- my read is that there are two ways to be eligible here:

1. Aged 18-39 AND they are a member of a family that received SNAP for the (continuous) 6 months prior to the hiring date.
2. Aged 18-39 AND they are ABAWD AND they are a member of a family that received SNAP for 3 consecutive months out of the past 5 prior to the hiring date.

The second one is the confusing one. I think this just has to do with the fact that if you don't have dependents in the household and are't working (but are able to work), then SNAP is time-limited so you can only get it for 3 months over the course of 3 years. So WOTC doesn't want to disqualify those people on the 6-month SNAP requirement, so instead they use a 3 month SNAP requirement.

So what should we do to identify ABAWD? Maybe for now we just apply the "3 months out of the past 5 months" to everyone (i.e., our working definition of eligibility is aged 18-39 AND they are a member of a family that received SNAP for 3 months out of the past 5), and then come back to this later to see what other datasets might have the ABAWD information so we can be more precise. My guess is it will be somewhere in the WADC data (demographic info?). Also should we make the requirement consecutive 3 months, or just any 3 months of the last 5?

Jeff, what do you think? Manisha, does that make sense?

**Comment by jbweaver** [comment]
Thanks both for thinking this through so carefully! I like Corina's solution of applying the 3 months out of the past 5 for everyone for now and then coming back later to see what other data sets have ABAWD information to figure that out. 

two other thoughts:
1) In the short-run, it would be useful to know how different the samples look if we use the 3 month vs 6 month definition -- my guess is that they will be pretty similar in which case we don't have to worry about that.
2) For defining dependents, the easiest option may be to use the FSmem variables in the food stamp data set (which has the number of members of the family getting food stamps). We can't see if the other members are dependents, but we would know for sure that they don't have dependents if that field is equal to zero.

**Comment by cmommaerts** [comment]
1. Hmm... My understanding is that SNAP is a household/family level benefit
(is that right, Jeff/Manisha?), so in that case it probably depends how the
data is organized. What is a "primary person"? Maybe this is a discussion
item for Thursday...

2 and 3. I don't think we have gotten access to the crime data or the WOTC
data -- it should be coming soon!

**Comment by jbweaver** [comment]
re 1 -- that is my understanding too -- does the codebook say anything about this? Another way to check this would be to count the total number of SNAP beneficiaries in a given month in the data and compare to the statewide DHS counts from files here (https://www.dhs.wisconsin.gov/foodshare/rsdata.htm) to see whether it looks like we are getting all eligible adults.

**Comment by manishajain3** [comment]
yes, it is at the household level (the benefit amount is per case which i guess means family/HH) rather than at the individual level. In the data, I can see a CaseID and all IDs of all the individuals associated with that case (one row identified by CaseID and Individual ID). The data are wide (different columns for different month-years). In any month-year, there is a "Primary Person" (I don't know how PP is defined by SNAP) of that case who may or may not be eligible for SNAP (every individual has a PPCode which takes the value 0 if they are the PP of that case but not eligible for SNAP in this month-year, 1 if they are the PP and eligible for SNAP in that month-year, 2 if they are eligible for SNAP in that month-year but not PP). The Primary Person can change over time and the same person can also change from a non-eligible PP to an eligible PP. The PPCode has missing values as well (which I guess means that the case was not active in that month/year--eg if a case starts from March 2007 then it should have missing values in Jan and Feb 2007  or a non-PP person goes is ineligible in that month-year but eligible in at least one month in that year).

Since the files identify some individuals who are part of the family/case but not eligible for SNAP benefits themselve (i.e. those with PPCode=0), I thought that there could be some individuals who are part of the family, not the PP, and not eligible for the benefits themselves? 

Sorry if this does not make sense or is not relevant! It's just that I think SNAP-WOTC eligibility depends on whether someone's family is getting the benefits, even if they aren't themselves eligible

**Comment by manishajain3** [comment]
I'll check if the count matches the DHS counts

**Comment by jbweaver** [comment]
Thanks, this makes sense to me (I think)! Based on this, it sounds to me like we would want to code anyone with PPCode equal to either 1 or 2 for three of the previous five months as eligible due to SNAP. My understanding of the rules is that for cases where they are members of the family but not eligible for SNAP themselves, they would be unlikely to get WOTC -- it seems like it would be hard for them to prove that they are part of a family that is receiving SNAP (but not themselves receiving it). This is something that we can check once we get the WOTC data since that will have the reason for eligibility -- for now, maybe let's use PPCode of 1 or 2, and then we can update that if needed when we have the WOTC data?

**Comment by jbweaver** [comment]
and no need to check the match to the DHS counts- - I misunderstood and
your reply made it clear! sorry about that not good suggestion.

**Comment by manishajain3** [comment]
[wadc.docx](https://github.com/jbweaver/wotc/files/9478892/wadc.docx)
